version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.1
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: nollup
    versions:
    - 0.14.4
    - 0.15.0
    - 0.15.1
    - 0.15.2
    - 0.15.3
    - 0.15.5
    - 0.15.6
    - 0.16.0
    - 0.16.1
  - dependency-name: three
    versions:
    - 0.125.1
    - 0.125.2
    - 0.126.0
    - 0.126.1
    - 0.127.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.16.1
  - dependency-name: rollup-plugin-static-files
    versions:
    - 0.1.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: rollup-plugin-postcss
    versions:
    - 3.1.8
