// import 'ts-polyfill/lib/es2016-array-include'
// import 'ts-polyfill/lib/es2017-object'
// import 'ts-polyfill/lib/es2017-string'
// import 'ts-polyfill/lib/es2018-async-iterable'
// import 'ts-polyfill/lib/es2018-promise'
// import 'ts-polyfill/lib/es2019-array'
// import 'ts-polyfill/lib/es2019-object'
// import 'ts-polyfill/lib/es2019-string'
// import 'ts-polyfill/lib/es2019-symbol'
// import 'ts-polyfill/lib/es2020-promise'
// import 'ts-polyfill/lib/es2020-string'
// import 'ts-polyfill/lib/es2020-symbol-wellknown'
// import 'ts-polyfill/lib/es2020-global-this'

// import '@webcomponents/webcomponentsjs'
// import '@webcomponents/webcomponentsjs/webcomponents-loader'
